# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: github-toy

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    - rm -rf ./dist
builds:
  - env:
      - CGO_ENABLED=0
      - GO11MODULE=on
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true

brews:
  - name: github-toy
    github:
      owner: yukihirop
      name: homebrew-github-toy
    folder: Formula
    description: Toy to operate github
    homepage: https://github.com/yukihirop/github-toy
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    dependencies:
      - go
    install: |
      bin.install "gtoy"
    test: |
      system "#{bin}/gtoy"
